package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/MakeNowJust/heredoc/v2"
	"github.com/cloudspannerecosystem/memefish/tools/util/astcatalog"
)

var (
	usage = heredoc.Doc(`
		Usage of tools/gen-ast-expr-impls.go

		A generator of ast/expr_impls_test.go.

		Example:

		  $ go run ./tools/gen-ast-expr-impls/main.go -astfile ast/ast.go -constfile ast/ast_const.go
		        Print the generated ast/expr_impls_test.go to stdout.

		Flags:
	`)
	prologue = heredoc.Doc(`
		// Code generated by tools/gen-ast-expr-impls; DO NOT EDIT.

		package ast

		type exprPrecTestCase struct {
			name string
			expr Expr
		}

		var exprPrecTestCases = []exprPrecTestCase{
	`)
)

var (
	astfile   = flag.String("astfile", "ast/ast.go", "path to ast/ast.go")
	constfile = flag.String("constfile", "ast/ast_const.go", "path to ast/ast_const.go")
	outfile   = flag.String("outfile", "", "output filename (if it is not specified, the result is printed to stdout.)")
)

func main() {
	flag.Usage = func() {
		fmt.Print(usage)
		flag.PrintDefaults()
	}

	flag.Parse()

	catalog, err := astcatalog.Load(*astfile, *constfile)
	if err != nil {
		log.Fatal(err)
	}

	exprInterface := catalog.Interfaces[astcatalog.NodeInterfaceType("Expr")]
	if exprInterface == nil {
		log.Fatal("Expr interface is not registered in AST catalog")
	}

	var buffer bytes.Buffer
	buffer.WriteString(prologue)

	for _, typ := range exprInterface.Implemented {
		fmt.Fprintf(&buffer, "\t{name: %q, expr: %s},\n", typ, exprPrecTestExprLiteral(typ))
	}
	fmt.Fprintln(&buffer, "}")

	if *outfile == "" {
		fmt.Print(buffer.String())
		return
	}

	err = os.WriteFile(*outfile, buffer.Bytes(), 0666)
	if err != nil {
		log.Fatal(err)
	}
}

func exprPrecTestExprLiteral(typ astcatalog.NodeStructType) string {
	switch typ {
	case "BinaryExpr":
		return "&BinaryExpr{Op: OpAdd}"
	case "UnaryExpr":
		return "&UnaryExpr{Op: OpMinus}"
	default:
		return fmt.Sprintf("&%s{}", typ)
	}
}
