create table foo (
    id int64 generated by default as identity (
        bit_reversed_positive start counter with 1000 skip range 1, 12345),
    startCount int64 generated by default as identity (
        bit_reversed_positive start counter with 1000),
    skipRange int64 generated by default as identity (
        bit_reversed_positive skip range 1000, 2000),
    simple int64 generated by default as identity ( bit_reversed_positive),
) primary key (id)
