// Code generated by tools/gen-ast-expr-impls; DO NOT EDIT.

package ast

type exprPrecTestCase struct {
	name string
	expr Expr
}

var exprPrecTestCases = []exprPrecTestCase{
	{name: "BadExpr", expr: &BadExpr{}},
	{name: "BinaryExpr", expr: &BinaryExpr{Op: OpAdd}},
	{name: "UnaryExpr", expr: &UnaryExpr{Op: OpMinus}},
	{name: "InExpr", expr: &InExpr{}},
	{name: "IsNullExpr", expr: &IsNullExpr{}},
	{name: "IsBoolExpr", expr: &IsBoolExpr{}},
	{name: "IsSourceExpr", expr: &IsSourceExpr{}},
	{name: "IsDestinationExpr", expr: &IsDestinationExpr{}},
	{name: "IsLabeledExpr", expr: &IsLabeledExpr{}},
	{name: "BetweenExpr", expr: &BetweenExpr{}},
	{name: "SelectorExpr", expr: &SelectorExpr{}},
	{name: "IndexExpr", expr: &IndexExpr{}},
	{name: "CallExpr", expr: &CallExpr{}},
	{name: "CountStarExpr", expr: &CountStarExpr{}},
	{name: "CastExpr", expr: &CastExpr{}},
	{name: "ExtractExpr", expr: &ExtractExpr{}},
	{name: "WithExpr", expr: &WithExpr{}},
	{name: "ReplaceFieldsExpr", expr: &ReplaceFieldsExpr{}},
	{name: "CaseExpr", expr: &CaseExpr{}},
	{name: "IfExpr", expr: &IfExpr{}},
	{name: "ParenExpr", expr: &ParenExpr{}},
	{name: "ScalarSubQuery", expr: &ScalarSubQuery{}},
	{name: "ArraySubQuery", expr: &ArraySubQuery{}},
	{name: "ExistsSubQuery", expr: &ExistsSubQuery{}},
	{name: "Param", expr: &Param{}},
	{name: "Ident", expr: &Ident{}},
	{name: "Path", expr: &Path{}},
	{name: "ArrayLiteral", expr: &ArrayLiteral{}},
	{name: "TupleStructLiteral", expr: &TupleStructLiteral{}},
	{name: "TypelessStructLiteral", expr: &TypelessStructLiteral{}},
	{name: "TypedStructLiteral", expr: &TypedStructLiteral{}},
	{name: "NullLiteral", expr: &NullLiteral{}},
	{name: "BoolLiteral", expr: &BoolLiteral{}},
	{name: "IntLiteral", expr: &IntLiteral{}},
	{name: "FloatLiteral", expr: &FloatLiteral{}},
	{name: "StringLiteral", expr: &StringLiteral{}},
	{name: "BytesLiteral", expr: &BytesLiteral{}},
	{name: "DateLiteral", expr: &DateLiteral{}},
	{name: "TimestampLiteral", expr: &TimestampLiteral{}},
	{name: "NumericLiteral", expr: &NumericLiteral{}},
	{name: "JSONLiteral", expr: &JSONLiteral{}},
	{name: "IntervalLiteralSingle", expr: &IntervalLiteralSingle{}},
	{name: "IntervalLiteralRange", expr: &IntervalLiteralRange{}},
	{name: "NewConstructor", expr: &NewConstructor{}},
	{name: "BracedNewConstructor", expr: &BracedNewConstructor{}},
	{name: "BracedConstructor", expr: &BracedConstructor{}},
}
